-- Migration 004: Add prompt_source column to rounds table
-- Tracks whether each round's prompt was generated by LLM or template fallback.

ALTER TABLE rounds ADD COLUMN IF NOT EXISTS prompt_source VARCHAR(20) DEFAULT 'template';
