/**
 * Word bank seed data.
 * Populates the word_bank table with 650+ diverse, image-generation-friendly words
 * across 15+ categories. Uses upsert (ON CONFLICT DO NOTHING) to be idempotent.
 *
 * Usage: npm run seed
 */

import dotenv from "dotenv";
dotenv.config();

import { pool, closePool } from "../../config/database";
import type { WordSeedEntry } from "../../models/wordBank";

// ---------------------------------------------------------------------------
// Seed Data — 500+ words across 15+ categories
// ---------------------------------------------------------------------------

const SEED_WORDS: WordSeedEntry[] = [
  // =========================================================================
  // ANIMALS (40 words) — common, recognizable animals
  // =========================================================================
  { word: "cat", category: "animals" },
  { word: "dog", category: "animals" },
  { word: "elephant", category: "animals" },
  { word: "whale", category: "animals" },
  { word: "penguin", category: "animals" },
  { word: "frog", category: "animals" },
  { word: "bear", category: "animals" },
  { word: "horse", category: "animals" },
  { word: "cow", category: "animals" },
  { word: "pig", category: "animals" },
  { word: "chicken", category: "animals" },
  { word: "duck", category: "animals" },
  { word: "monkey", category: "animals" },
  { word: "giraffe", category: "animals" },
  { word: "lion", category: "animals" },
  { word: "tiger", category: "animals" },
  { word: "shark", category: "animals" },
  { word: "dolphin", category: "animals" },
  { word: "turtle", category: "animals" },
  { word: "rabbit", category: "animals" },
  { word: "snake", category: "animals" },
  { word: "owl", category: "animals" },
  { word: "eagle", category: "animals" },
  { word: "parrot", category: "animals" },
  { word: "octopus", category: "animals" },
  { word: "jellyfish", category: "animals" },
  { word: "flamingo", category: "animals" },
  { word: "corgi", category: "animals" },
  { word: "panda", category: "animals" },
  { word: "koala", category: "animals" },
  { word: "raccoon", category: "animals" },
  { word: "squirrel", category: "animals" },
  { word: "deer", category: "animals" },
  { word: "hamster", category: "animals" },
  { word: "goldfish", category: "animals" },
  { word: "crab", category: "animals" },
  { word: "butterfly", category: "animals" },
  { word: "bee", category: "animals" },
  { word: "snail", category: "animals" },
  { word: "goat", category: "animals" },
  { word: "alpaca", category: "animals" },
  { word: "hedgehog", category: "animals" },
  { word: "pelican", category: "animals" },
  { word: "chameleon", category: "animals" },
  { word: "lobster", category: "animals" },
  { word: "ostrich", category: "animals" },
  { word: "beaver", category: "animals" },
  { word: "sloth", category: "animals" },
  { word: "seahorse", category: "animals" },
  { word: "iguana", category: "animals" },
  { word: "chipmunk", category: "animals" },
  { word: "armadillo", category: "animals" },
  { word: "walrus", category: "animals" },
  { word: "platypus", category: "animals" },
  { word: "moose", category: "animals" },
  { word: "otter", category: "animals" },
  { word: "toucan", category: "animals" },
  { word: "porcupine", category: "animals" },
  { word: "wombat", category: "animals" },
  { word: "mole", category: "animals" },
  { word: "stork", category: "animals" },
  { word: "badger", category: "animals" },
  { word: "gecko", category: "animals" },
  { word: "shrimp", category: "animals" },

  // =========================================================================
  // OBJECTS (40+ words) — everyday items anyone would recognize
  // =========================================================================
  { word: "umbrella", category: "objects" },
  { word: "guitar", category: "objects" },
  { word: "bicycle", category: "objects" },
  { word: "skateboard", category: "objects" },
  { word: "chair", category: "objects" },
  { word: "lamp", category: "objects" },
  { word: "clock", category: "objects" },
  { word: "mirror", category: "objects" },
  { word: "book", category: "objects" },
  { word: "hat", category: "objects" },
  { word: "crown", category: "objects" },
  { word: "wand", category: "objects" },
  { word: "telescope", category: "objects" },
  { word: "camera", category: "objects" },
  { word: "ladder", category: "objects" },
  { word: "balloon", category: "objects" },
  { word: "bucket", category: "objects" },
  { word: "key", category: "objects" },
  { word: "shovel", category: "objects" },
  { word: "broom", category: "objects" },
  { word: "candle", category: "objects" },
  { word: "trophy", category: "objects" },
  { word: "flag", category: "objects" },
  { word: "kite", category: "objects" },
  { word: "backpack", category: "objects" },
  { word: "paintbrush", category: "objects" },
  { word: "fishing rod", category: "objects" },
  { word: "watering can", category: "objects" },
  { word: "megaphone", category: "objects" },
  { word: "microphone", category: "objects" },
  { word: "trampoline", category: "objects" },
  { word: "treasure chest", category: "objects" },
  { word: "magnifying glass", category: "objects" },
  { word: "shopping cart", category: "objects" },
  { word: "wheelbarrow", category: "objects" },
  { word: "bathtub", category: "objects" },
  { word: "piano", category: "objects" },
  { word: "phone", category: "objects" },
  { word: "toilet", category: "objects" },
  { word: "bed", category: "objects" },
  { word: "typewriter", category: "objects" },
  { word: "birdcage", category: "objects" },
  { word: "fishbowl", category: "objects" },
  { word: "chandelier", category: "objects" },
  { word: "mailbox", category: "objects" },
  { word: "fire hydrant", category: "objects" },
  { word: "vending machine", category: "objects" },
  { word: "traffic cone", category: "objects" },
  { word: "lawn chair", category: "objects" },
  { word: "alarm clock", category: "objects" },
  { word: "blender", category: "objects" },
  { word: "catapult", category: "objects" },
  { word: "cuckoo clock", category: "objects" },
  { word: "disco ball", category: "objects" },
  { word: "easel", category: "objects" },
  { word: "globe", category: "objects" },
  { word: "jack-in-the-box", category: "objects" },
  { word: "lava lamp", category: "objects" },
  { word: "pinwheel", category: "objects" },
  { word: "pogo stick", category: "objects" },
  { word: "rubber duck", category: "objects" },
  { word: "snow globe", category: "objects" },
  { word: "stilts", category: "objects" },
  { word: "sundial", category: "objects" },
  { word: "whoopee cushion", category: "objects" },
  { word: "yo-yo", category: "objects" },
  { word: "plunger", category: "objects" },
  { word: "anvil", category: "objects" },
  { word: "slingshot", category: "objects" },
  { word: "binoculars", category: "objects" },
  { word: "hourglass", category: "objects" },
  { word: "spinning wheel", category: "objects" },
  { word: "piggy bank", category: "objects" },
  { word: "pinata", category: "objects" },
  { word: "beanbag chair", category: "objects" },

  // =========================================================================
  // FOODS (30+ words) — universally known foods
  // =========================================================================
  { word: "pizza", category: "foods" },
  { word: "ice cream", category: "foods" },
  { word: "banana", category: "foods" },
  { word: "cake", category: "foods" },
  { word: "donut", category: "foods" },
  { word: "hamburger", category: "foods" },
  { word: "hot dog", category: "foods" },
  { word: "sandwich", category: "foods" },
  { word: "spaghetti", category: "foods" },
  { word: "taco", category: "foods" },
  { word: "cookie", category: "foods" },
  { word: "watermelon", category: "foods" },
  { word: "pineapple", category: "foods" },
  { word: "apple", category: "foods" },
  { word: "cupcake", category: "foods" },
  { word: "pancake", category: "foods" },
  { word: "waffle", category: "foods" },
  { word: "popcorn", category: "foods" },
  { word: "french fries", category: "foods" },
  { word: "sushi", category: "foods" },
  { word: "burrito", category: "foods" },
  { word: "pretzel", category: "foods" },
  { word: "lollipop", category: "foods" },
  { word: "cotton candy", category: "foods" },
  { word: "cheese", category: "foods" },
  { word: "bread", category: "foods" },
  { word: "avocado", category: "foods" },
  { word: "cherry", category: "foods" },
  { word: "coconut", category: "foods" },
  { word: "egg", category: "foods" },
  { word: "corn dog", category: "foods" },
  { word: "muffin", category: "foods" },
  { word: "pie", category: "foods" },
  { word: "jelly", category: "foods" },
  { word: "nachos", category: "foods" },
  { word: "popsicle", category: "foods" },
  { word: "bagel", category: "foods" },
  { word: "pudding", category: "foods" },
  { word: "grapes", category: "foods" },
  { word: "pickle", category: "foods" },
  { word: "cinnamon roll", category: "foods" },
  { word: "gummy bear", category: "foods" },
  { word: "fried chicken", category: "foods" },
  { word: "milkshake", category: "foods" },
  { word: "marshmallow", category: "foods" },
  { word: "candy cane", category: "foods" },
  { word: "toast", category: "foods" },
  { word: "onion ring", category: "foods" },
  { word: "drumstick", category: "foods" },

  // =========================================================================
  // ACTIONS (35+ words) — simple, visual verbs
  // =========================================================================
  { word: "riding", category: "actions" },
  { word: "eating", category: "actions" },
  { word: "dancing", category: "actions" },
  { word: "flying", category: "actions" },
  { word: "sleeping", category: "actions" },
  { word: "juggling", category: "actions" },
  { word: "surfing", category: "actions" },
  { word: "painting", category: "actions" },
  { word: "cooking", category: "actions" },
  { word: "singing", category: "actions" },
  { word: "swimming", category: "actions" },
  { word: "jumping", category: "actions" },
  { word: "running", category: "actions" },
  { word: "climbing", category: "actions" },
  { word: "fishing", category: "actions" },
  { word: "skiing", category: "actions" },
  { word: "skating", category: "actions" },
  { word: "reading", category: "actions" },
  { word: "driving", category: "actions" },
  { word: "holding", category: "actions" },
  { word: "diving", category: "actions" },
  { word: "skateboarding", category: "actions" },
  { word: "bowling", category: "actions" },
  { word: "throwing", category: "actions" },
  { word: "catching", category: "actions" },
  { word: "chasing", category: "actions" },
  { word: "hiding", category: "actions" },
  { word: "sliding", category: "actions" },
  { word: "balancing", category: "actions" },
  { word: "spinning", category: "actions" },
  { word: "digging", category: "actions" },
  { word: "building", category: "actions" },
  { word: "playing", category: "actions" },
  { word: "waving", category: "actions" },
  { word: "melting", category: "actions" },
  { word: "stacking", category: "actions" },
  { word: "shrinking", category: "actions" },
  { word: "growing", category: "actions" },
  { word: "exploding", category: "actions" },
  { word: "dripping", category: "actions" },
  { word: "rolling", category: "actions" },
  { word: "folding", category: "actions" },
  { word: "pouring", category: "actions" },
  { word: "squeezing", category: "actions" },
  { word: "tiptoeing", category: "actions" },
  { word: "sneezing", category: "actions" },
  { word: "yawning", category: "actions" },
  { word: "bouncing", category: "actions" },
  { word: "crawling", category: "actions" },
  { word: "marching", category: "actions" },
  { word: "leaping", category: "actions" },
  { word: "dragging", category: "actions" },
  { word: "flexing", category: "actions" },
  { word: "sweeping", category: "actions" },
  { word: "knitting", category: "actions" },
  { word: "ironing", category: "actions" },
  { word: "mopping", category: "actions" },
  { word: "shoveling", category: "actions" },
  { word: "whispering", category: "actions" },
  { word: "pointing", category: "actions" },
  { word: "squatting", category: "actions" },
  { word: "hugging", category: "actions" },
  { word: "shaking", category: "actions" },
  { word: "peeking", category: "actions" },
  { word: "saluting", category: "actions" },
  { word: "snoring", category: "actions" },
  { word: "tap dancing", category: "actions" },
  { word: "carrying", category: "actions" },

  // =========================================================================
  // ADJECTIVES (30+ words) — simple, visual descriptors
  // =========================================================================
  { word: "giant", category: "adjectives" },
  { word: "tiny", category: "adjectives" },
  { word: "purple", category: "adjectives" },
  { word: "golden", category: "adjectives" },
  { word: "fluffy", category: "adjectives" },
  { word: "old", category: "adjectives" },
  { word: "shiny", category: "adjectives" },
  { word: "broken", category: "adjectives" },
  { word: "floating", category: "adjectives" },
  { word: "frozen", category: "adjectives" },
  { word: "upside-down", category: "adjectives" },
  { word: "rainbow", category: "adjectives" },
  { word: "crooked", category: "adjectives" },
  { word: "glowing", category: "adjectives" },
  { word: "rusty", category: "adjectives" },
  { word: "wooden", category: "adjectives" },
  { word: "rubber", category: "adjectives" },
  { word: "sleepy", category: "adjectives" },
  { word: "angry", category: "adjectives" },
  { word: "confused", category: "adjectives" },
  { word: "scared", category: "adjectives" },
  { word: "happy", category: "adjectives" },
  { word: "grumpy", category: "adjectives" },
  { word: "sparkly", category: "adjectives" },
  { word: "striped", category: "adjectives" },
  { word: "polka-dot", category: "adjectives" },
  { word: "baby", category: "adjectives" },
  { word: "robotic", category: "adjectives" },
  { word: "hairy", category: "adjectives" },
  { word: "inflatable", category: "adjectives" },
  { word: "soggy", category: "adjectives" },
  { word: "tangled", category: "adjectives" },
  { word: "wobbly", category: "adjectives" },
  { word: "squished", category: "adjectives" },
  { word: "enormous", category: "adjectives" },
  { word: "backwards", category: "adjectives" },
  { word: "stretchy", category: "adjectives" },
  { word: "lumpy", category: "adjectives" },
  { word: "muddy", category: "adjectives" },
  { word: "slimy", category: "adjectives" },
  { word: "dizzy", category: "adjectives" },
  { word: "wrinkled", category: "adjectives" },
  { word: "chubby", category: "adjectives" },
  { word: "spiky", category: "adjectives" },
  { word: "fuzzy", category: "adjectives" },
  { word: "cracked", category: "adjectives" },
  { word: "spotted", category: "adjectives" },
  { word: "see-through", category: "adjectives" },
  { word: "flat", category: "adjectives" },

  // =========================================================================
  // SETTINGS / PLACES (30+ words) — recognizable everyday + fun locations
  // =========================================================================
  { word: "beach", category: "settings" },
  { word: "kitchen", category: "settings" },
  { word: "moon", category: "settings" },
  { word: "grocery store", category: "settings" },
  { word: "park", category: "settings" },
  { word: "mountain", category: "settings" },
  { word: "castle", category: "settings" },
  { word: "farm", category: "settings" },
  { word: "hospital", category: "settings" },
  { word: "school", category: "settings" },
  { word: "library", category: "settings" },
  { word: "museum", category: "settings" },
  { word: "zoo", category: "settings" },
  { word: "circus", category: "settings" },
  { word: "playground", category: "settings" },
  { word: "space", category: "settings" },
  { word: "ocean", category: "settings" },
  { word: "rooftop", category: "settings" },
  { word: "garden", category: "settings" },
  { word: "cave", category: "settings" },
  { word: "island", category: "settings" },
  { word: "city", category: "settings" },
  { word: "forest", category: "settings" },
  { word: "desert", category: "settings" },
  { word: "swamp", category: "settings" },
  { word: "volcano", category: "settings" },
  { word: "airport", category: "settings" },
  { word: "train station", category: "settings" },
  { word: "bowling alley", category: "settings" },
  { word: "aquarium", category: "settings" },
  { word: "laundromat", category: "settings" },
  { word: "elevator", category: "settings" },
  { word: "parking lot", category: "settings" },
  { word: "dentist office", category: "settings" },
  { word: "movie theater", category: "settings" },
  { word: "gas station", category: "settings" },
  { word: "treehouse", category: "settings" },
  { word: "ice cream shop", category: "settings" },
  { word: "subway", category: "settings" },
  { word: "attic", category: "settings" },
  { word: "basement", category: "settings" },
  { word: "bathroom", category: "settings" },
  { word: "garage", category: "settings" },
  { word: "junkyard", category: "settings" },
  { word: "barn", category: "settings" },
  { word: "bakery", category: "settings" },
  { word: "pet store", category: "settings" },
  { word: "waiting room", category: "settings" },
  { word: "construction site", category: "settings" },
  { word: "campsite", category: "settings" },
  { word: "igloo", category: "settings" },
  { word: "lighthouse", category: "settings" },
  { word: "courtroom", category: "settings" },
  { word: "haunted house", category: "settings" },
  { word: "diner", category: "settings" },
  { word: "arcade", category: "settings" },
  { word: "waterpark", category: "settings" },
  { word: "pirate ship", category: "settings" },
  { word: "space station", category: "settings" },
  { word: "shopping mall", category: "settings" },
  { word: "football field", category: "settings" },
  { word: "boxing ring", category: "settings" },
  { word: "hot air balloon", category: "settings" },
  { word: "submarine", category: "settings" },
  { word: "roller coaster", category: "settings" },
  { word: "candy factory", category: "settings" },
  { word: "car wash", category: "settings" },
  { word: "skatepark", category: "settings" },
  { word: "tennis court", category: "settings" },
  { word: "swimming pool", category: "settings" },
  { word: "wedding", category: "settings" },
  { word: "opera house", category: "settings" },
  { word: "sushi restaurant", category: "settings" },
  { word: "pizza shop", category: "settings" },
  { word: "fire station", category: "settings" },
  { word: "police station", category: "settings" },
  { word: "clock tower", category: "settings" },
  { word: "bridge", category: "settings" },
  { word: "windmill", category: "settings" },
  { word: "trampoline park", category: "settings" },
  { word: "ferris wheel", category: "settings" },
  { word: "hair salon", category: "settings" },
  { word: "greenhouse", category: "settings" },
  { word: "helicopter", category: "settings" },
  { word: "hot spring", category: "settings" },
  { word: "skateboard ramp", category: "settings" },
  { word: "ice rink", category: "settings" },
  { word: "corn maze", category: "settings" },
  { word: "dump truck", category: "settings" },
  { word: "office", category: "settings" },
  { word: "gym", category: "settings" },
  { word: "spa", category: "settings" },
  { word: "roof", category: "settings" },
  { word: "tunnel", category: "settings" },
  { word: "boat", category: "settings" },
  { word: "stage", category: "settings" },
  { word: "market", category: "settings" },
  { word: "alley", category: "settings" },
  { word: "balcony", category: "settings" },
  { word: "dock", category: "settings" },
  { word: "fountain", category: "settings" },
  { word: "jungle", category: "settings" },
  { word: "glacier", category: "settings" },
  { word: "canyon", category: "settings" },
  { word: "coral reef", category: "settings" },
  { word: "meadow", category: "settings" },
  { word: "waterfall", category: "settings" },
  { word: "volcano crater", category: "settings" },
  { word: "rice paddy", category: "settings" },
  { word: "pond", category: "settings" },
  { word: "highway", category: "settings" },
  { word: "bus stop", category: "settings" },
  { word: "escape room", category: "settings" },
  { word: "photo booth", category: "settings" },
  { word: "launchpad", category: "settings" },
  { word: "throne room", category: "settings" },
  { word: "dungeon", category: "settings" },
  { word: "washing machine", category: "settings" },
  { word: "bathtub", category: "settings" },
  { word: "bunk bed", category: "settings" },
  { word: "closet", category: "settings" },
  { word: "staircase", category: "settings" },
  { word: "escalator", category: "settings" },
  { word: "revolving door", category: "settings" },
  { word: "rooftop pool", category: "settings" },
  { word: "treehouse fort", category: "settings" },
  { word: "hammock", category: "settings" },
  { word: "picnic blanket", category: "settings" },
  { word: "shopping cart", category: "settings" },
  { word: "taxi cab", category: "settings" },
  { word: "school bus", category: "settings" },
  { word: "ambulance", category: "settings" },
  { word: "fire truck", category: "settings" },
  { word: "sailboat", category: "settings" },
  { word: "canoe", category: "settings" },
  { word: "rowboat", category: "settings" },
  { word: "ski lift", category: "settings" },
  { word: "ski slope", category: "settings" },
  { word: "golf course", category: "settings" },
  { word: "baseball diamond", category: "settings" },
  { word: "basketball court", category: "settings" },
  { word: "hockey rink", category: "settings" },
  { word: "race track", category: "settings" },
  { word: "wrestling ring", category: "settings" },
  { word: "karate dojo", category: "settings" },
  { word: "dance studio", category: "settings" },
  { word: "recording studio", category: "settings" },
  { word: "art studio", category: "settings" },
  { word: "pottery wheel", category: "settings" },
  { word: "science lab", category: "settings" },
  { word: "locker room", category: "settings" },
  { word: "classroom", category: "settings" },
  { word: "cafeteria", category: "settings" },
  { word: "food truck", category: "settings" },
  { word: "taco stand", category: "settings" },
  { word: "lemonade stand", category: "settings" },
  { word: "donut shop", category: "settings" },
  { word: "coffee shop", category: "settings" },
  { word: "barbershop", category: "settings" },
  { word: "tattoo parlor", category: "settings" },
  { word: "post office", category: "settings" },
  { word: "bank vault", category: "settings" },
  { word: "pawn shop", category: "settings" },
  { word: "flea market", category: "settings" },
  { word: "thrift store", category: "settings" },
  { word: "toy store", category: "settings" },
  { word: "pet shop", category: "settings" },
  { word: "flower shop", category: "settings" },
  { word: "car dealership", category: "settings" },
  { word: "junkyard crane", category: "settings" },
  { word: "recycling plant", category: "settings" },
  { word: "power plant", category: "settings" },
  { word: "water tower", category: "settings" },
  { word: "radio tower", category: "settings" },
  { word: "control room", category: "settings" },
  { word: "cockpit", category: "settings" },
  { word: "blimp", category: "settings" },
  { word: "hot dog cart", category: "settings" },
  { word: "merry-go-round", category: "settings" },
  { word: "bounce house", category: "settings" },
  { word: "ball pit", category: "settings" },
  { word: "go-kart track", category: "settings" },
  { word: "mini golf course", category: "settings" },
  { word: "bowling lane", category: "settings" },
  { word: "dart board", category: "settings" },
  { word: "poker table", category: "settings" },
  { word: "chess board", category: "settings" },
  { word: "sandbox", category: "settings" },
  { word: "tree stump", category: "settings" },
  { word: "bird nest", category: "settings" },
  { word: "ant hill", category: "settings" },
  { word: "beehive", category: "settings" },
  { word: "spider web", category: "settings" },
  { word: "mushroom patch", category: "settings" },
  { word: "bamboo forest", category: "settings" },
  { word: "sunflower field", category: "settings" },
  { word: "cherry blossom tree", category: "settings" },
  { word: "cactus garden", category: "settings" },
  { word: "lily pad", category: "settings" },
  { word: "iceberg", category: "settings" },
  { word: "sandcastle", category: "settings" },
  { word: "tide pool", category: "settings" },
  { word: "shipwreck", category: "settings" },
  { word: "treasure chest", category: "settings" },
  { word: "wishing well", category: "settings" },
  { word: "phone booth", category: "settings" },
  { word: "porta potty", category: "settings" },
  { word: "vending machine", category: "settings" },
  { word: "conveyor belt", category: "settings" },
  { word: "assembly line", category: "settings" },
  { word: "red carpet", category: "settings" },
  { word: "runway", category: "settings" },
  { word: "parade float", category: "settings" },
  { word: "concert stage", category: "settings" },
  { word: "DJ booth", category: "settings" },
  { word: "karaoke bar", category: "settings" },
  { word: "bingo hall", category: "settings" },
  { word: "dentist chair", category: "settings" },
  { word: "barber chair", category: "settings" },
  { word: "lifeguard tower", category: "settings" },
  { word: "observation deck", category: "settings" },
  { word: "drawbridge", category: "settings" },
  { word: "moat", category: "settings" },
  { word: "crater", category: "settings" },
  { word: "quicksand", category: "settings" },
  { word: "rain cloud", category: "settings" },
  { word: "rainbow", category: "settings" },
  { word: "northern lights", category: "settings" },
  { word: "tornado", category: "settings" },
  { word: "avalanche", category: "settings" },
  { word: "tightrope", category: "settings" },
  { word: "trapeze", category: "settings" },
  { word: "diving board", category: "settings" },
  { word: "water slide", category: "settings" },
  { word: "lazy river", category: "settings" },

  // =========================================================================
  // PROFESSIONS (20+ words) — universally known roles
  // =========================================================================
  { word: "astronaut", category: "professions" },
  { word: "pirate", category: "professions" },
  { word: "cowboy", category: "professions" },
  { word: "ninja", category: "professions" },
  { word: "chef", category: "professions" },
  { word: "firefighter", category: "professions" },
  { word: "doctor", category: "professions" },
  { word: "teacher", category: "professions" },
  { word: "wizard", category: "professions" },
  { word: "clown", category: "professions" },
  { word: "farmer", category: "professions" },
  { word: "mailman", category: "professions" },
  { word: "knight", category: "professions" },
  { word: "robot", category: "professions" },
  { word: "superhero", category: "professions" },
  { word: "detective", category: "professions" },
  { word: "king", category: "professions" },
  { word: "queen", category: "professions" },
  { word: "pilot", category: "professions" },
  { word: "lifeguard", category: "professions" },
  { word: "librarian", category: "professions" },
  { word: "janitor", category: "professions" },
  { word: "dentist", category: "professions" },
  { word: "plumber", category: "professions" },
  { word: "mechanic", category: "professions" },
  { word: "referee", category: "professions" },
  { word: "ballerina", category: "professions" },
  { word: "lumberjack", category: "professions" },
  { word: "zookeeper", category: "professions" },
  { word: "weatherman", category: "professions" },

  // =========================================================================
  // VEHICLES (20+ words) — easy to picture
  // =========================================================================
  { word: "car", category: "vehicles" },
  { word: "bus", category: "vehicles" },
  { word: "train", category: "vehicles" },
  { word: "airplane", category: "vehicles" },
  { word: "helicopter", category: "vehicles" },
  { word: "boat", category: "vehicles" },
  { word: "spaceship", category: "vehicles" },
  { word: "submarine", category: "vehicles" },
  { word: "motorcycle", category: "vehicles" },
  { word: "truck", category: "vehicles" },
  { word: "bicycle", category: "vehicles" },
  { word: "hot air balloon", category: "vehicles" },
  { word: "rocket", category: "vehicles" },
  { word: "canoe", category: "vehicles" },
  { word: "tractor", category: "vehicles" },
  { word: "fire truck", category: "vehicles" },
  { word: "taxi", category: "vehicles" },
  { word: "scooter", category: "vehicles" },
  { word: "sled", category: "vehicles" },
  { word: "roller coaster", category: "vehicles" },
  { word: "skateboard", category: "vehicles" },
  { word: "unicycle", category: "vehicles" },
  { word: "zamboni", category: "vehicles" },
  { word: "golf cart", category: "vehicles" },
  { word: "ambulance", category: "vehicles" },
  { word: "tugboat", category: "vehicles" },
  { word: "go-kart", category: "vehicles" },
  { word: "monster truck", category: "vehicles" },
  { word: "ice cream truck", category: "vehicles" },
  { word: "sailboat", category: "vehicles" },

  // =========================================================================
  // NATURE (20+ words) — simple natural things
  // =========================================================================
  { word: "tree", category: "nature" },
  { word: "cloud", category: "nature" },
  { word: "rainbow", category: "nature" },
  { word: "sun", category: "nature" },
  { word: "star", category: "nature" },
  { word: "flower", category: "nature" },
  { word: "mushroom", category: "nature" },
  { word: "cactus", category: "nature" },
  { word: "waterfall", category: "nature" },
  { word: "river", category: "nature" },
  { word: "lightning", category: "nature" },
  { word: "snowflake", category: "nature" },
  { word: "tornado", category: "nature" },
  { word: "rain", category: "nature" },
  { word: "sunset", category: "nature" },
  { word: "boulder", category: "nature" },
  { word: "sunflower", category: "nature" },
  { word: "vine", category: "nature" },
  { word: "wave", category: "nature" },
  { word: "volcano", category: "nature" },
  { word: "coral reef", category: "nature" },
  { word: "iceberg", category: "nature" },
  { word: "seashell", category: "nature" },
  { word: "pebble", category: "nature" },
  { word: "moss", category: "nature" },
  { word: "pond", category: "nature" },
  { word: "creek", category: "nature" },
  { word: "cliff", category: "nature" },
  { word: "meadow", category: "nature" },
  { word: "bamboo", category: "nature" },
  { word: "tumbleweed", category: "nature" },
  { word: "geyser", category: "nature" },
  { word: "aurora borealis", category: "nature" },
  { word: "stalactite", category: "nature" },
  { word: "sand dune", category: "nature" },
  { word: "tide pool", category: "nature" },
  { word: "beehive", category: "nature" },
  { word: "pinecone", category: "nature" },
  { word: "lily pad", category: "nature" },
  { word: "cobweb", category: "nature" },

  // =========================================================================
  // BODY PARTS (15+ words) — fun visual modifiers
  // =========================================================================
  { word: "wings", category: "body parts" },
  { word: "tail", category: "body parts" },
  { word: "horns", category: "body parts" },
  { word: "mustache", category: "body parts" },
  { word: "tentacles", category: "body parts" },
  { word: "claws", category: "body parts" },
  { word: "feathers", category: "body parts" },
  { word: "skeleton", category: "body parts" },
  { word: "eyeball", category: "body parts" },
  { word: "fangs", category: "body parts" },
  { word: "paws", category: "body parts" },
  { word: "beak", category: "body parts" },
  { word: "antlers", category: "body parts" },
  { word: "extra arms", category: "body parts" },
  { word: "spots", category: "body parts" },
  { word: "scales", category: "body parts" },
  { word: "fins", category: "body parts" },
  { word: "tusks", category: "body parts" },
  { word: "whiskers", category: "body parts" },
  { word: "hooves", category: "body parts" },
  { word: "spines", category: "body parts" },
  { word: "trunk", category: "body parts" },
  { word: "shell", category: "body parts" },
  { word: "mane", category: "body parts" },
  { word: "stinger", category: "body parts" },
  { word: "flippers", category: "body parts" },
  { word: "gills", category: "body parts" },
  { word: "pouch", category: "body parts" },
  { word: "hump", category: "body parts" },

  // =========================================================================
  // MATERIALS (15+ words) — simple, everyday materials
  // =========================================================================
  { word: "glass", category: "materials" },
  { word: "chocolate", category: "materials" },
  { word: "cheese", category: "materials" },
  { word: "ice", category: "materials" },
  { word: "jelly", category: "materials" },
  { word: "paper", category: "materials" },
  { word: "rubber", category: "materials" },
  { word: "wood", category: "materials" },
  { word: "gold", category: "materials" },
  { word: "diamond", category: "materials" },
  { word: "bubblegum", category: "materials" },
  { word: "slime", category: "materials" },
  { word: "lava", category: "materials" },
  { word: "cotton candy", category: "materials" },
  { word: "cardboard", category: "materials" },
  { word: "marshmallow", category: "materials" },
  { word: "bubble wrap", category: "materials" },
  { word: "duct tape", category: "materials" },
  { word: "tinfoil", category: "materials" },
  { word: "velvet", category: "materials" },
  { word: "concrete", category: "materials" },
  { word: "foam", category: "materials" },
  { word: "sandpaper", category: "materials" },
  { word: "clay", category: "materials" },

  // =========================================================================
  // COLORS (15+ words) — basic colors everyone knows
  // =========================================================================
  { word: "red", category: "colors" },
  { word: "blue", category: "colors" },
  { word: "green", category: "colors" },
  { word: "yellow", category: "colors" },
  { word: "orange", category: "colors" },
  { word: "purple", category: "colors" },
  { word: "pink", category: "colors" },
  { word: "golden", category: "colors" },
  { word: "silver", category: "colors" },
  { word: "white", category: "colors" },
  { word: "black", category: "colors" },
  { word: "rainbow", category: "colors" },
  { word: "neon", category: "colors" },
  { word: "glowing", category: "colors" },
  { word: "striped", category: "colors" },
  { word: "teal", category: "colors" },
  { word: "magenta", category: "colors" },
  { word: "turquoise", category: "colors" },
  { word: "maroon", category: "colors" },
  { word: "beige", category: "colors" },
  { word: "coral", category: "colors" },
  { word: "lavender", category: "colors" },
  { word: "bronze", category: "colors" },
  { word: "crimson", category: "colors" },
  { word: "tan", category: "colors" },

  // =========================================================================
  // WEATHER (15+ words) — simple weather everyone knows
  // =========================================================================
  { word: "thunderstorm", category: "weather" },
  { word: "tornado", category: "weather" },
  { word: "blizzard", category: "weather" },
  { word: "rainbow", category: "weather" },
  { word: "fog", category: "weather" },
  { word: "lightning", category: "weather" },
  { word: "rain", category: "weather" },
  { word: "snow", category: "weather" },
  { word: "sunshine", category: "weather" },
  { word: "hail", category: "weather" },
  { word: "wind", category: "weather" },
  { word: "clouds", category: "weather" },
  { word: "hurricane", category: "weather" },
  { word: "flood", category: "weather" },
  { word: "sunset", category: "weather" },
  { word: "drizzle", category: "weather" },
  { word: "frost", category: "weather" },
  { word: "sleet", category: "weather" },
  { word: "heat wave", category: "weather" },
  { word: "mist", category: "weather" },
  { word: "dust storm", category: "weather" },
  { word: "aurora", category: "weather" },
  { word: "moonlight", category: "weather" },
  { word: "starlight", category: "weather" },
  { word: "dawn", category: "weather" },

  // =========================================================================
  // CLOTHING (15+ words) — simple wearable items
  // =========================================================================
  { word: "top hat", category: "clothing" },
  { word: "cowboy hat", category: "clothing" },
  { word: "sunglasses", category: "clothing" },
  { word: "cape", category: "clothing" },
  { word: "scarf", category: "clothing" },
  { word: "boots", category: "clothing" },
  { word: "flip flops", category: "clothing" },
  { word: "tutu", category: "clothing" },
  { word: "crown", category: "clothing" },
  { word: "bow tie", category: "clothing" },
  { word: "overalls", category: "clothing" },
  { word: "apron", category: "clothing" },
  { word: "helmet", category: "clothing" },
  { word: "roller skates", category: "clothing" },
  { word: "diaper", category: "clothing" },
  { word: "monocle", category: "clothing" },
  { word: "snorkel", category: "clothing" },
  { word: "life jacket", category: "clothing" },
  { word: "lab coat", category: "clothing" },
  { word: "toga", category: "clothing" },
  { word: "sombrero", category: "clothing" },
  { word: "suspenders", category: "clothing" },
  { word: "mittens", category: "clothing" },
  { word: "bandana", category: "clothing" },
  { word: "goggles", category: "clothing" },

  // =========================================================================
  // MUSICAL INSTRUMENTS (15+ words) — well-known instruments
  // =========================================================================
  { word: "guitar", category: "musical instruments" },
  { word: "piano", category: "musical instruments" },
  { word: "drums", category: "musical instruments" },
  { word: "trumpet", category: "musical instruments" },
  { word: "banjo", category: "musical instruments" },
  { word: "tuba", category: "musical instruments" },
  { word: "violin", category: "musical instruments" },
  { word: "harmonica", category: "musical instruments" },
  { word: "xylophone", category: "musical instruments" },
  { word: "accordion", category: "musical instruments" },
  { word: "tambourine", category: "musical instruments" },
  { word: "ukulele", category: "musical instruments" },
  { word: "cowbell", category: "musical instruments" },
  { word: "maracas", category: "musical instruments" },
  { word: "saxophone", category: "musical instruments" },
  { word: "flute", category: "musical instruments" },
  { word: "bagpipes", category: "musical instruments" },
  { word: "triangle", category: "musical instruments" },
  { word: "kazoo", category: "musical instruments" },
  { word: "bongos", category: "musical instruments" },
  { word: "harp", category: "musical instruments" },
  { word: "trombone", category: "musical instruments" },
  { word: "cello", category: "musical instruments" },
  { word: "recorder", category: "musical instruments" },
  { word: "didgeridoo", category: "musical instruments" },

  // =========================================================================
  // MYTHICAL CREATURES (15 words) — well-known fantasy beings
  // =========================================================================
  { word: "dragon", category: "mythical creatures" },
  { word: "unicorn", category: "mythical creatures" },
  { word: "mermaid", category: "mythical creatures" },
  { word: "yeti", category: "mythical creatures" },
  { word: "phoenix", category: "mythical creatures" },
  { word: "griffin", category: "mythical creatures" },
  { word: "centaur", category: "mythical creatures" },
  { word: "troll", category: "mythical creatures" },
  { word: "fairy", category: "mythical creatures" },
  { word: "goblin", category: "mythical creatures" },
  { word: "gnome", category: "mythical creatures" },
  { word: "kraken", category: "mythical creatures" },
  { word: "cyclops", category: "mythical creatures" },
  { word: "minotaur", category: "mythical creatures" },
  { word: "sasquatch", category: "mythical creatures" },

  // =========================================================================
  // EMOTIONS (10 words) — visible facial expressions
  // =========================================================================
  { word: "surprised", category: "emotions" },
  { word: "suspicious", category: "emotions" },
  { word: "embarrassed", category: "emotions" },
  { word: "proud", category: "emotions" },
  { word: "nervous", category: "emotions" },
  { word: "excited", category: "emotions" },
  { word: "shocked", category: "emotions" },
  { word: "smug", category: "emotions" },
  { word: "bored", category: "emotions" },
  { word: "panicked", category: "emotions" },

  // =========================================================================
  // STYLES (10 words) — recognizable visual styles
  // =========================================================================
  { word: "pixel art", category: "styles" },
  { word: "cartoon", category: "styles" },
  { word: "watercolor", category: "styles" },
  { word: "crayon drawing", category: "styles" },
  { word: "oil painting", category: "styles" },
  { word: "chalk drawing", category: "styles" },
  { word: "comic book", category: "styles" },
  { word: "stained glass", category: "styles" },
  { word: "clay sculpture", category: "styles" },
  { word: "paper cutout", category: "styles" },
];

// ---------------------------------------------------------------------------
// Seed function
// ---------------------------------------------------------------------------

/**
 * Seed the word_bank table with curated words.
 * Uses INSERT ... ON CONFLICT DO NOTHING for idempotent re-seeding.
 */
export async function seedWordBank(): Promise<{ inserted: number; total: number }> {
  console.log(`[seed] Seeding word bank with ${SEED_WORDS.length} words...`);

  const client = await pool.connect();
  let inserted = 0;

  try {
    await client.query("BEGIN");

    for (const entry of SEED_WORDS) {
      const result = await client.query(
        `INSERT INTO word_bank (word, category)
         VALUES ($1, $2)
         ON CONFLICT (word) DO NOTHING`,
        [entry.word, entry.category]
      );
      if (result.rowCount && result.rowCount > 0) {
        inserted++;
      }
    }

    await client.query("COMMIT");

    // Get total count
    const countResult = await client.query("SELECT COUNT(*) FROM word_bank");
    const total = parseInt(countResult.rows[0].count, 10);

    console.log(`[seed] Inserted ${inserted} new words. Total in bank: ${total}`);
    return { inserted, total };
  } catch (err) {
    await client.query("ROLLBACK");
    throw err;
  } finally {
    client.release();
  }
}

/** Export the seed data for testing and validation. */
export { SEED_WORDS };

// ---------------------------------------------------------------------------
// CLI runner
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  try {
    const { inserted, total } = await seedWordBank();

    // Report category breakdown
    const categories = new Map<string, number>();
    for (const entry of SEED_WORDS) {
      categories.set(entry.category, (categories.get(entry.category) || 0) + 1);
    }
    console.log(`[seed] Categories (${categories.size}):`);
    for (const [cat, count] of categories.entries()) {
      console.log(`  - ${cat}: ${count} words`);
    }

    console.log(`\n[seed] Done. ${inserted} new words inserted, ${total} total in database.`);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[seed] Seed failed:", message);
    process.exit(1);
  } finally {
    await closePool();
  }
}

main();
